### ISSUE TITLE
SQL Value marshall/unmarshall is broken

### ISSUE THREAD

**Issue by risentveber** [shopspring/decimal#152] opened 2019-10-04 15:38 UTC
Get error when used with gorm:

```
pq: encode: unknown type for decimal.Decimal
```

All nice on commit: cd690d0c9e2447b1ef2a129a6b7b49077da89b8e
but broken for the last one: a36b5d85f337bcbff4008ffb786d0e4ec2a345a4

Also, it would be nice if you will add go mod support.

**Comment by risentveber** [comment] 2019-10-04 15:43
```bash
➜  decimal git:(master) git diff cd690d0..a36b5d8 --name-only | cat
.travis.yml
decomposer.go
decomposer_test.go
```
seems like something is wrong in decomposer.go file

**Comment by risentveber** [comment] 2019-10-07 13:38
See also https://github.com/golang/go/issues/34315

**Comment by njason** [comment] 2019-11-25 04:09
commit 75bb2cb has been reverted from master and will be worked on in another branch

**Comment by risentveber** [comment] 2019-11-25 08:06
@njason maybe it's time to add go modules with versioning?

**Comment by mwoss** [comment] 2019-11-25 08:11
@risentveber We will do it in our next iteration. Stay tuned

**Comment by andskor** [comment] 2020-11-02 17:51
@mwoss  any update?

**Comment by mwoss** [comment] 2020-11-02 22:21
I've tried to recall where our discussion with Jason ended on that, but I'm not quite sure. I have a vague memory that we were waiting for the response from `lib/pq` maintainers, but I could be wrong. @njason could you elaborate?

**Comment by njason** [comment] 2020-11-20 04:18
Using the [decomposer-interface branch](https://github.com/shopspring/decimal/tree/decomposer-interface), which contains the [PR](https://github.com/shopspring/decimal/pull/141) that was previously reverted from `master`, I am still able to reproduce the [encoding issue](https://github.com/golang/go/issues/34315#issue-493821454) (with go 1.13, latest version of `lib/pq`). The issue is occurring because [this encode function](https://github.com/lib/pq/blob/083382b7e6fc78cc91eb57afab268fe2f1b6ed6d/encode.go#L31) in `lib/pq` does not support the shopspring Decimal type. @kardianos [made a suggestion](https://github.com/golang/go/issues/30870#issuecomment-717358078) for a solution that would require database drivers to recognize the decomposer type.

I believe this issue should be closed since SQL value marshalling is no longer broken on `master`. For now, we can keep the `decomposer-interface` branch and continue to work with the go community to support the `decomposer` interface when possible.

**Comment by mwoss** [comment] 2020-11-22 12:34
Thanks for the detailed explanation, Jason :D 
Let's wait for a couple of days before closing the issue, so @andskor and @risentveber will be able to respond to it.

**Comment by risentveber** [comment] 2020-11-22 15:45
@mwoss yeah you can close - tnanks)

**Closed** 2020-11-23 14:58 UTC
