### ISSUE TITLE
Truncate has error

### ISSUE THREAD

**Issue by 599259501** [shopspring/decimal#187] opened 2020-10-26 06:41 UTC
input:1.29
ouput:1.28

**Comment by mwoss** [comment] 2020-10-26 23:07
Hi @599259501. Could you elaborate on that? Could just share a code snippet?

**Comment by mwoss** [comment] 2020-11-24 00:16
I'm closing this issue ticket for now as the author did not respond and I'm not able to reproduce this bug.

**Closed by mwoss** 2020-11-24 00:16 UTC
